### ISSUE TITLE
Automate table creation

### ISSUE THREAD

**Issue by mrobbeloth** [NathanShort1998/Energy-Made-Easy#7]
Should have script files to automate the creation of your database tables. Look at https://github.com/mrobbeloth/daycare/tree/main/mock for examples (the SQL files in particular)

**Comment by NathanShort1998** [comment]
I have some files to do this, I just have several and I want to get rid of unnecessary ones and assign the good ones better names.

**Comment by NathanShort1998** [comment]
Including these in the branch "Final Submission"
