### ISSUE TITLE
Database credentials in source

### ISSUE THREAD

**Issue by mrobbeloth** [NathanShort1998/Energy-Made-Easy#8]
You have database connection credentials in your source. These should be loaded from an ini file that is kept locally and copied to the web/database server with appropriate permissions for reading/writing.

**Comment by NathanShort1998** [comment]
Finally implemented ini files with personal credentials. I don't have creds that are not mine. I would need new ones that I can put into the ini file.

**Comment by NathanShort1998** [comment]
I will look into how to configure the ini file to restrict access to group & world

**Comment by NathanShort1998** [comment]
Finished this
